### ISSUE TITLE
Improvement suggestion for CI/CD scripts

### ISSUE THREAD

**Issue by yaruno** [Eyevinn/node-srt#68]
To counter introducing regressions in future via pull requests I recommend to modify test running script [nodejs.yml](https://github.com/Eyevinn/node-srt/blob/master/.github/workflows/nodejs.yml) to include trigger that runs tests against pull requests when they are introduced.

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request

Currently:

```
name: Node CI
  
on: [push]

jobs:
@@@rest of the script@@@
```

Suggestion:

```
name: Node CI
on:
  push:
  pull_request:

jobs:
@@@rest of the script@@@
```
